apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: smartdish
type: Opaque
stringData:
  MYSQL_HOST: "${MYSQL_HOST}"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "smartdish"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-secrets
  namespace: smartdish-prod
type: Opaque
stringData:
  MYSQL_HOST: "${MYSQL_HOST}"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "smartdish"
  MYSQL_USER: "${MYSQL_USER}"
  MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
  MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"

