apiVersion: v1
kind: Namespace
metadata:
  name: smartdish
  labels:
    name: smartdish
    environment: integration
---
apiVersion: v1
kind: Namespace
metadata:
  name: smartdish-prod
  labels:
    name: smartdish-prod
    environment: production

