# Configuration pour l'environnement de production
replicaCount: 2

image:
  tag: "production"

ingress:
  hosts:
    - host: soa-{{ .Values.microserviceName }}.smartdish.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: smartdish-prod-tls
      hosts:
        - "*.smartdish.cloud"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "production"
  - name: LOG_LEVEL
    value: "INFO"
  - name: LOG_LEVEL_JDBC
    value: "WARN"

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 512Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 80

