# Configuration pour l'environnement d'int√©gration
replicaCount: 1

image:
  tag: "integration"

ingress:
  hosts:
    - host: soa-{{ .Values.microserviceName }}-integration.smartdish-integration.cloud
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: smartdish-integration-tls
      hosts:
        - "*.smartdish-integration.cloud"

env:
  - name: SPRING_PROFILES_ACTIVE
    value: "integration"
  - name: LOG_LEVEL
    value: "DEBUG"
  - name: LOG_LEVEL_JDBC
    value: "DEBUG"

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

